"""
Memory tools for the EatFit Agent.

Backed by PostgreSQL + pgvector. Every active memory has a 1024-dim
embedding generated by ollama (qwen3-embedding:0.6b). Recall uses one
of four pluggable retrievers (vector / importance / hybrid / fulltext);
hybrid is the production default. Full-text uses pg tsvector populated
from jieba-segmented Chinese text (migration 008).
"""

import logging
from typing import Dict, Any, List, Optional

import jieba
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.memory import MemoryItem
from app.services.embedding_service import embed_text_sync, vec_literal
from app.tools.retrievers import REGISTRY as RETRIEVER_REGISTRY, _safe_float_or_none

logger = logging.getLogger(__name__)


def tokenize_zh(text_in: str) -> str:
    """Segment Chinese text via jieba into a space-separated string.

    Output feeds `to_tsvector('simple', ...)` — the 'simple' config just
    lowercases and splits on whitespace, so pre-tokenized CJK text is
    indexed as proper words instead of single characters.
    """
    if not text_in:
        return ""
    return " ".join(t.strip() for t in jieba.cut(text_in) if t and t.strip())


class MemoryTools:
    """Tools for managing user memories in the agent system."""

    MEMORY_TYPES = [
        "preference", "allergy_intolerance",
    ]

    HIGH_IMPORTANCE_TYPES = [
        "allergy_intolerance",
    ]

    def __init__(self, db: Session):
        self.db = db

    # ---------- 读取 ----------

    def get_active_memories(self, user_id: int, memory_types: Optional[List[str]] = None,
                            limit: int = 20) -> List[Dict[str, Any]]:
        """Get active memories ordered by importance desc, then created_at desc."""
        query = self.db.query(MemoryItem).filter(
            MemoryItem.user_id == user_id,
            MemoryItem.status == "active",
        )
        if memory_types:
            query = query.filter(MemoryItem.memory_type.in_(memory_types))
        rows = query.order_by(MemoryItem.importance_score.desc(), MemoryItem.created_at.desc()).limit(limit).all()
        return [self._memory_to_dict(m) for m in rows]

    def get_relevant_memories(self, user_id: int, intent: str, limit: int = 10,
                              query_text: Optional[str] = None,
                              retriever: str = "hybrid") -> List[Dict[str, Any]]:
        """
        Multi-mode memory recall. Default retriever is "hybrid" (production).

        `query_text` is the text to embed / fulltext-search. If omitted
        (legacy callers), the intent string itself is used — semantically
        meaningless. Production callers MUST pass the actual user message.

        `retriever` selects the ranking strategy:
          - "vector":    pure pgvector cosine similarity
          - "importance": pure importance_score ordering (no Ollama)
          - "hybrid":    vw * vector + iw * importance  (production default)
          - "fulltext":  tsvector + ts_rank  (requires migration 008)
        """
        # After migration 009, only 2 types remain. Both are always recallable
        # for any intent (filtering by type is no longer meaningful since the
        # split is now "soft preference vs hard medical constraint").
        intent_memory_map = {
            "diet_advice":     ["preference", "allergy_intolerance"],
            "meal_log":        ["preference", "allergy_intolerance"],
            "profile_update":  ["preference", "allergy_intolerance"],
            "dashboard_query": ["preference", "allergy_intolerance"],
        }
        memory_types = intent_memory_map.get(intent)

        embed_text = query_text if query_text else intent
        if not query_text:
            logger.warning(
                "get_relevant_memories called without query_text (intent=%s); "
                "falling back to intent string as embedding query — semantic "
                "recall will degenerate. Pass query_text=context.message.",
                intent,
            )

        retriever_cls = RETRIEVER_REGISTRY.get(retriever)
        if retriever_cls is None:
            logger.warning("Unknown retriever %r, falling back to hybrid", retriever)
            retriever_cls = RETRIEVER_REGISTRY["hybrid"]
        try:
            rows = retriever_cls.retrieve(self.db, user_id, embed_text, memory_types, limit)
        except Exception as e:
            logger.warning("retriever %s failed, fallback to ORM: %s", retriever, e)
            return self.get_active_memories(user_id, memory_types, limit)

        # Batch-touch last_used_at — same NOW() for every row hit by this recall
        # (matches the original _hybrid_search semantics).
        if rows:
            ids = [r["id"] for r in rows]
            try:
                self.db.execute(
                    text("UPDATE memory_items SET last_used_at = NOW() WHERE id = ANY(:ids)"),
                    {"ids": ids},
                )
                self.db.commit()
            except Exception as e:
                logger.warning("last_used_at batch touch failed: %s", e)
                self.db.rollback()

        return rows

    # Back-compat alias: keep `_hybrid_search` reachable for any external caller
    # that might still reference it. Same as `get_relevant_memories(retriever="hybrid")`.
    def _hybrid_search(self, user_id: int, query_text: str,
                       memory_types: Optional[List[str]], limit: int) -> List[Dict[str, Any]]:
        return self.get_relevant_memories(
            user_id=user_id,
            intent="",  # not used by direct retriever path; only intent_memory_map is, and
                         # callers passing memory_types directly bypass it.
            limit=limit,
            query_text=query_text,
            retriever="hybrid",
        )

    # ---------- 写入 ----------

    def create_memory(self, user_id: int, memory_type: str, content: str, importance_score: int = 5,
                      source: str = "auto_extracted", source_message_id: Optional[int] = None,
                      confidence_score: float = 0.8, metadata: Optional[Dict] = None) -> MemoryItem:
        """Create a new memory item; populate jieba-segmented content + embedding."""
        memory = MemoryItem(
            user_id=user_id,
            memory_type=memory_type,
            content=content,
            content_zh=tokenize_zh(content),
            importance_score=importance_score,
            source=source,
            source_message_id=source_message_id,
            confidence_score=confidence_score,
            status="active",
            metadata_json=metadata,
            embedding_status="pending",
        )
        self.db.add(memory)
        self.db.flush()  # get id; trigger populates content_tsv from content_zh

        self.embed_memory(memory.id, content)

        self.db.commit()
        self.db.refresh(memory)
        return memory

    def update_memory(self, memory_id: int, user_id: int, content: Optional[str] = None,
                      memory_type: Optional[str] = None, importance_score: Optional[int] = None) -> Optional[MemoryItem]:
        """Update a memory's content or properties; re-embed + re-segment if content changed."""
        memory = self.db.query(MemoryItem).filter(
            MemoryItem.id == memory_id, MemoryItem.user_id == user_id
        ).first()
        if not memory:
            return None

        content_changed = False
        if content is not None and content != memory.content:
            memory.content = content
            memory.content_zh = tokenize_zh(content)
            content_changed = True
        if memory_type is not None:
            memory.memory_type = memory_type
        if importance_score is not None:
            memory.importance_score = importance_score

        if content_changed:
            self.embed_memory(memory.id, memory.content)
            # Refresh tsvector explicitly — the trigger fires on content change but
            # also refresh content_zh-driven path so fulltext retriever sees the new tokens.
            self.db.execute(
                text("UPDATE memory_items SET content_tsv = to_tsvector('simple', content_zh) WHERE id = :id"),
                {"id": memory.id},
            )

        self.db.commit()
        self.db.refresh(memory)
        return memory

    def confirm_memory(self, memory_id: int, user_id: int) -> Optional[MemoryItem]:
        memory = self.db.query(MemoryItem).filter(
            MemoryItem.id == memory_id, MemoryItem.user_id == user_id
        ).first()
        if not memory:
            return None
        memory.status = "active"
        self.embed_memory(memory.id, memory.content)
        self.db.commit()
        self.db.refresh(memory)
        return memory

    def embed_memory(self, memory_id: int, content: str) -> None:
        """Re-embed an existing memory row. Used by REST endpoints that
        bypass create_memory (POST /api/memories when the user confirms a
        pending card, PUT /api/memories/{id} on edit)."""
        try:
            vec = embed_text_sync(content)
            self.db.execute(
                text("""
                    UPDATE memory_items
                    SET embedding = CAST(:vec AS vector),
                        embedding_status = 'ready',
                        embedding_updated_at = NOW()
                    WHERE id = :id
                """),
                {"vec": vec_literal(vec), "id": memory_id},
            )
            self.db.commit()
        except Exception as e:
            logger.error("Failed to write embedding for memory %s: %s", memory_id, e)
            try:
                self.db.execute(
                    text("UPDATE memory_items SET embedding_status = 'failed' WHERE id = :id"),
                    {"id": memory_id},
                )
                self.db.commit()
            except Exception:
                self.db.rollback()
                raise

    # ---------- Public helpers ----------

    def create_pending_memory(self, user_id: int, memory_type: str, content: str,
                              importance_score: int = 5, source: str = "auto_extracted",
                              source_message_id: Optional[int] = None,
                              confidence_score: float = 0.8) -> Dict[str, Any]:
        is_high_importance = memory_type in self.HIGH_IMPORTANCE_TYPES
        return {
            "memory_type": memory_type,
            "content": content,
            "importance_score": importance_score,
            "confidence_score": confidence_score,
            "source": source,
            "source_message_id": source_message_id,
            "is_high_importance": is_high_importance,
            "display_text": self._generate_memory_confirm_text(memory_type, content, is_high_importance),
        }

    # ---------- Private helpers ----------

    def _memory_to_dict(self, m: MemoryItem) -> Dict[str, Any]:
        return self._row_to_dict({
            "id": m.id, "user_id": m.user_id, "memory_type": m.memory_type,
            "content": m.content, "importance_score": m.importance_score,
            "confidence_score": m.confidence_score, "source": m.source,
            "source_message_id": m.source_message_id, "status": m.status,
            "last_used_at": m.last_used_at, "created_at": m.created_at,
            "updated_at": m.updated_at, "metadata_json": m.metadata_json,
            "embedding_status": m.embedding_status, "embedding_updated_at": m.embedding_updated_at,
        })

    def _row_to_dict(self, r: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "id": r["id"],
            "user_id": r.get("user_id"),
            "memory_type": r["memory_type"],
            "content": r["content"],
            "importance_score": r["importance_score"],
            "confidence_score": float(r["confidence_score"]) if r.get("confidence_score") is not None else 0.8,
            "source": r["source"],
            "source_message_id": r.get("source_message_id"),
            "status": r["status"],
            "last_used_at": r["last_used_at"].isoformat() if r.get("last_used_at") else None,
            "created_at": r["created_at"].isoformat() if r.get("created_at") else None,
            "updated_at": r["updated_at"].isoformat() if r.get("updated_at") else None,
            "metadata": r.get("metadata_json"),
            "embedding_status": r.get("embedding_status"),
            "similarity": _safe_float_or_none(r.get("similarity")),
            "score": _safe_float_or_none(r.get("score")),
        }

    def _generate_memory_confirm_text(self, memory_type: str, content: str, is_high_importance: bool) -> str:
        type_names = {
            "allergy_intolerance": "过敏/不耐受",
            "preference": "偏好",
        }
        type_name = type_names.get(memory_type, memory_type)
        if is_high_importance:
            return f"我可以记住：你{content}。以后推荐饮食时会参考这条信息。是否确认？"
        return f"记住：{type_name} - {content}"
