"""
Enhanced memory tools for the EatFit Agent.

Backed by PostgreSQL + pgvector. Every active memory has a 1024-dim
embedding generated by ollama (qwen3-embedding:0.6b). Recall uses a
hybrid score = importance_weight * (importance/10) + vector_weight * cosine_similarity.
"""

import logging
from typing import Dict, Any, List, Optional
from datetime import datetime

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.memory import MemoryItem
from app.services.embedding_service import embed_text, embed_text_sync, vec_literal

logger = logging.getLogger(__name__)


class MemoryTools:
    """Tools for managing user memories in the agent system."""

    MEMORY_TYPES = [
        "diet_preference", "food_dislike", "allergy_intolerance", "goal",
        "budget", "location", "scenario", "sleep", "body_response",
        "restriction", "habit", "other",
    ]

    HIGH_IMPORTANCE_TYPES = [
        "allergy_intolerance", "body_response", "goal", "restriction", "food_dislike",
    ]

    def __init__(self, db: Session):
        self.db = db

    # ---------- 读取 ----------

    def get_active_memories(self, user_id: int, memory_types: Optional[List[str]] = None,
                            limit: int = 20) -> List[Dict[str, Any]]:
        """Get active memories ordered by importance desc, then created_at desc."""
        query = self.db.query(MemoryItem).filter(
            MemoryItem.user_id == user_id,
            MemoryItem.status == "active",
        )
        if memory_types:
            query = query.filter(MemoryItem.memory_type.in_(memory_types))
        rows = query.order_by(MemoryItem.importance_score.desc(), MemoryItem.created_at.desc()).limit(limit).all()
        return [self._memory_to_dict(m) for m in rows]

    def get_relevant_memories(self, user_id: int, intent: str, limit: int = 10) -> List[Dict[str, Any]]:
        """
        Hybrid search: combine importance score and cosine similarity of embedding.

        Score = vector_weight * (1 - cosine_distance) + importance_weight * (importance/10)

        Falls back to importance-only ordering when:
        - user has no memories with embedding (cold start)
        - ollama is unavailable
        """
        intent_memory_map = {
            "diet_advice": ["goal", "diet_preference", "food_dislike", "allergy_intolerance",
                            "budget", "sleep", "restriction", "habit"],
            "meal_log":    ["habit", "scenario", "diet_preference"],
            "profile_update": ["goal", "budget", "restriction"],
            "dashboard_query": ["goal", "habit", "budget"],
        }
        memory_types = intent_memory_map.get(intent)
        query_text = intent  # 用 intent 文本做向量查询

        # 1) 走 ORM 拿所有候选（带 status='active' & 类型过滤），同时给 vector 列绑一份
        try:
            return self._hybrid_search(user_id, query_text, memory_types, limit)
        except Exception as e:
            logger.warning("hybrid_search failed, fallback to ORM: %s", e)
            return self.get_active_memories(user_id, memory_types, limit)

    def _hybrid_search(self, user_id: int, query_text: str,
                       memory_types: Optional[List[str]], limit: int) -> List[Dict[str, Any]]:
        query_vec = embed_text_sync(query_text)  # may be all-zeros on failure
        vec_str = vec_literal(query_vec)

        vw = settings.MEMORY_VECTOR_WEIGHT
        iw = settings.MEMORY_IMPORTANCE_WEIGHT

        # 评分公式：
        # score = vw * (1 - (embedding <=> vec))  +  iw * (importance_score / 10.0)
        # 当 embedding 为 NULL，pgvector 的 <=> 返回 NULL，coalesce 成 1（即最不相似），自然靠 importance 排序
        score_expr = (
            f"({vw} * (1 - COALESCE(embedding <=> CAST(:qvec AS vector), 1.0)))"
            f" + ({iw} * (importance_score::float / 10.0))"
        )

        sql = f"""
            SELECT id, user_id, memory_type, content, importance_score, confidence_score,
                   source, source_message_id, status, last_used_at, created_at, updated_at,
                   metadata_json, embedding_status, embedding_updated_at,
                   {score_expr} AS score,
                   COALESCE(1 - (embedding <=> CAST(:qvec AS vector)), 0.0) AS similarity
            FROM memory_items
            WHERE user_id = :uid
              AND status = 'active'
              {'AND memory_type = ANY(:mtypes)' if memory_types else ''}
            ORDER BY score DESC, importance_score DESC, created_at DESC
            LIMIT :lim
        """
        params = {"uid": user_id, "qvec": vec_str, "lim": limit}
        if memory_types:
            params["mtypes"] = memory_types

        rows = self.db.execute(text(sql), params).mappings().all()

        # 顺手把 last_used_at 标记
        if rows:
            ids = [r["id"] for r in rows]
            self.db.execute(
                text("UPDATE memory_items SET last_used_at = NOW() WHERE id = ANY(:ids)"),
                {"ids": ids},
            )
            self.db.commit()

        return [self._row_to_dict(r) for r in rows]

    # ---------- 写入 ----------

    def create_memory(self, user_id: int, memory_type: str, content: str, importance_score: int = 5,
                      source: str = "auto_extracted", source_message_id: Optional[int] = None,
                      confidence_score: float = 0.8, metadata: Optional[Dict] = None) -> MemoryItem:
        """Create a new memory item; generate embedding synchronously."""
        memory = MemoryItem(
            user_id=user_id,
            memory_type=memory_type,
            content=content,
            importance_score=importance_score,
            source=source,
            source_message_id=source_message_id,
            confidence_score=confidence_score,
            status="active",
            metadata_json=metadata,
            embedding_status="pending",
        )
        self.db.add(memory)
        self.db.flush()  # 拿到 id

        self._write_embedding(memory.id, content)

        self.db.commit()
        self.db.refresh(memory)
        return memory

    def update_memory(self, memory_id: int, user_id: int, content: Optional[str] = None,
                      memory_type: Optional[str] = None, importance_score: Optional[int] = None) -> Optional[MemoryItem]:
        """Update a memory's content or properties; re-embed if content changed."""
        memory = self.db.query(MemoryItem).filter(
            MemoryItem.id == memory_id, MemoryItem.user_id == user_id
        ).first()
        if not memory:
            return None

        content_changed = False
        if content is not None and content != memory.content:
            memory.content = content
            content_changed = True
        if memory_type is not None:
            memory.memory_type = memory_type
        if importance_score is not None:
            memory.importance_score = importance_score

        if content_changed:
            self._write_embedding(memory.id, memory.content)

        self.db.commit()
        self.db.refresh(memory)
        return memory

    def confirm_memory(self, memory_id: int, user_id: int) -> Optional[MemoryItem]:
        memory = self.db.query(MemoryItem).filter(
            MemoryItem.id == memory_id, MemoryItem.user_id == user_id
        ).first()
        if not memory:
            return None
        memory.status = "active"
        # 状态确认时确保有 embedding
        self._write_embedding(memory.id, memory.content)
        self.db.commit()
        self.db.refresh(memory)
        return memory

    def mark_memory_inactive(self, memory_id: int, user_id: int) -> bool:
        memory = self.db.query(MemoryItem).filter(
            MemoryItem.id == memory_id, MemoryItem.user_id == user_id
        ).first()
        if not memory:
            return False
        memory.status = "inactive"
        self.db.commit()
        return True

    def supersede_old_memory(self, user_id: int, memory_type: str, new_content: str) -> Optional[MemoryItem]:
        old = self.db.query(MemoryItem).filter(
            MemoryItem.user_id == user_id,
            MemoryItem.memory_type == memory_type,
            MemoryItem.status == "active",
        ).first()
        if old:
            old.status = "superseded"
            self.db.commit()
        return self.create_memory(
            user_id=user_id,
            memory_type=memory_type,
            content=new_content,
            importance_score=old.importance_score if old else 5,
            source="auto_extracted",
        )

    def update_last_used(self, memory_id: int) -> None:
        memory = self.db.query(MemoryItem).filter(MemoryItem.id == memory_id).first()
        if memory:
            memory.last_used_at = datetime.now()
            self.db.commit()

    # ---------- 辅助 ----------

    def _write_embedding(self, memory_id: int, content: str) -> None:
        """Embed content and write into the vector column + update status."""
        self.embed_memory(memory_id, content)

    def embed_memory(self, memory_id: int, content: str) -> None:
        """Public: re-embed an existing memory row. Used by REST endpoints
        that bypass MemoryTools.create_memory (POST /api/memories when the
        user confirms a pending card, PUT /api/memories/{id} on edit)."""
        try:
            vec = embed_text_sync(content)
            self.db.execute(
                text("""
                    UPDATE memory_items
                    SET embedding = CAST(:vec AS vector),
                        embedding_status = 'ready',
                        embedding_updated_at = NOW()
                    WHERE id = :id
                """),
                {"vec": vec_literal(vec), "id": memory_id},
            )
            self.db.commit()
        except Exception as e:
            logger.error("Failed to write embedding for memory %s: %s", memory_id, e)
            try:
                self.db.execute(
                    text("UPDATE memory_items SET embedding_status = 'failed' WHERE id = :id"),
                    {"id": memory_id},
                )
                self.db.commit()
            except Exception:
                self.db.rollback()
                raise

    def backfill_pending_embeddings(self, user_id: Optional[int] = None) -> int:
        """Re-embed rows with embedding_status IN ('pending','failed').
        Used to repair memories created via the REST path that never embedded."""
        params: Dict[str, Any] = {}
        where = "embedding_status IN ('pending','failed') AND content IS NOT NULL"
        if user_id is not None:
            where += " AND user_id = :uid"
            params["uid"] = user_id
        rows = self.db.execute(
            text(f"SELECT id, content FROM memory_items WHERE {where}"),
            params,
        ).mappings().all()
        for r in rows:
            self.embed_memory(r["id"], r["content"])
        return len(rows)

    def create_pending_memory(self, user_id: int, memory_type: str, content: str,
                              importance_score: int = 5, source: str = "auto_extracted",
                              source_message_id: Optional[int] = None,
                              confidence_score: float = 0.8) -> Dict[str, Any]:
        is_high_importance = memory_type in self.HIGH_IMPORTANCE_TYPES
        return {
            "memory_type": memory_type,
            "content": content,
            "importance_score": importance_score,
            "confidence_score": confidence_score,
            "source": source,
            "source_message_id": source_message_id,
            "is_high_importance": is_high_importance,
            "display_text": self._generate_memory_confirm_text(memory_type, content, is_high_importance),
        }

    def _memory_to_dict(self, m: MemoryItem) -> Dict[str, Any]:
        return self._row_to_dict({
            "id": m.id, "user_id": m.user_id, "memory_type": m.memory_type,
            "content": m.content, "importance_score": m.importance_score,
            "confidence_score": m.confidence_score, "source": m.source,
            "source_message_id": m.source_message_id, "status": m.status,
            "last_used_at": m.last_used_at, "created_at": m.created_at,
            "updated_at": m.updated_at, "metadata_json": m.metadata_json,
            "embedding_status": m.embedding_status, "embedding_updated_at": m.embedding_updated_at,
        })

    def _row_to_dict(self, r: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "id": r["id"],
            "user_id": r.get("user_id"),
            "memory_type": r["memory_type"],
            "content": r["content"],
            "importance_score": r["importance_score"],
            "confidence_score": float(r["confidence_score"]) if r.get("confidence_score") is not None else 0.8,
            "source": r["source"],
            "source_message_id": r.get("source_message_id"),
            "status": r["status"],
            "last_used_at": r["last_used_at"].isoformat() if r.get("last_used_at") else None,
            "created_at": r["created_at"].isoformat() if r.get("created_at") else None,
            "updated_at": r["updated_at"].isoformat() if r.get("updated_at") else None,
            "metadata": r.get("metadata_json"),
            "embedding_status": r.get("embedding_status"),
            "similarity": float(r["similarity"]) if r.get("similarity") is not None else None,
            "score": float(r["score"]) if r.get("score") is not None else None,
        }

    def _generate_memory_confirm_text(self, memory_type: str, content: str, is_high_importance: bool) -> str:
        type_names = {
            "allergy_intolerance": "过敏/不耐受", "diet_preference": "饮食偏好",
            "food_dislike": "不喜欢食物", "goal": "长期目标", "budget": "预算偏好",
            "location": "常用位置", "scenario": "饮食场景", "sleep": "睡眠相关",
            "body_response": "身体反应", "restriction": "现实限制",
            "habit": "饮食习惯", "other": "其他",
        }
        type_name = type_names.get(memory_type, memory_type)
        if is_high_importance:
            return f"我可以记住：你{content}。以后推荐饮食时会参考这条信息。是否确认？"
        return f"记住：{type_name} - {content}"
